.TH DVIPRINT "1" "November 2003" "dviprint" "User Commands"
.SH NAME
\fIdviprint\fR \- \fIdvips\R\| wrapper for LyX
.SH SYNOPSIS
.B dviprint
[<dvips arguments>]
.SH DESCRIPTION
\fIdviprint\fR is a wrapper around \fIdvips\fR\|(1) that adjusts the
destination file and printer arguments (\-o and \-P) to handle variations
in install configurations (e. g., whether dvips sends its output
directly to a printer or writes to a file).  It is part of the Debian
packaging of the LyX editor.
.SH "SEE ALSO"
\fIdvips\fR\|(1), \fIlyx\fR\|(1)
