.TH NOWEB2LYX "1" "November 2003" "noweb2lyx" "User Commands"
.SH NAME
\fInoweb2lyx\fR \- convert a noweb literate program to a LyX document
.SH SYNOPSIS
.B noweb2lyx
[\-pre | \-post] \fI<input file> <output file>\fR
.SH DESCRIPTION
\fInoweb2lyx\fR translates a document written in the syntax of the
\fInoweb\fR literate programming tool into a LyX document.  It operates
by pre-processing the input file into LaTeX content, running the LaTeX
through reLyX to generate a LyX document, and post-processing the result
to restore additional formatting details.
.PP
If \fB\-pre\fR is specified, only pre-processes the input-file for reLyX.
Similarly, in the case of \fB\-post\fR, post-processes reLyX output.
These options allow the user to tune the document before and after the
reLyX stage.
.SH "SEE ALSO"
\fInoweb\fR\|(1), \fIrelyx\fR\|(1), \fIlyx\fR\|(1)
.SH "AUTHOR"
Kayvan Sylvan <kayvan@sylvan.com>
