/* -*- C++ -*- */
/**
 * \file version.cpp
 * This file is part of LyX, the document processor.
 * Licence details can be found in the file COPYING.
 *
 * \author Jean-Marc Lasgouttes
 *
 * Full author contact details are available in file CREDITS.
 *
 * Warning! This file is autogenerated from version.cpp.in.
 * All changes to this file will be lost.
 */

///
char const * lyx_version = "1.5.4";
///
char const * lyx_release_date = "Mon, Feb 25, 2008";

/// This is the version information shown by 'lyx -version'
char const * lyx_version_info = "Configuration\n  Host type:                    i686-pc-linux-gnu\n  Special build flags:          pch  use-ispell\n  C   Compiler:                 gcc \n  C   Compiler LyX flags:        \n  C   Compiler flags:             -O2\n  C++ Compiler:                 g++ (4.2.1)\n  C++ Compiler LyX flags:        \n  C++ Compiler flags:             -O2\n  Linker flags:                 \n  Linker user flags:            \n  Qt 4 Frontend:\n      Qt 4 version:\t\t4.3.1\n  Packaging:                    posix\n  LyX binary dir:               /usr/local/bin\n  LyX files dir:                /usr/local/share/lyx\n";
