#!/bin/sh

# pod2man --section=1 --release="Debian" --center=" " --date="28 June 2006"

error () {
    echo "$@" 1>&2
    exit 1
}


help () {
    echo "Usage: update-lyxrc [ --user ]"
    exit 1
}


configure () {
    test -d "$1" || error "Can't find directory $1"
    cd "$1" || exit 1
    /usr/share/lyx/configure.py
}


user () {
    configure "$HOME/.lyx"
}


if [ "$#" -gt 1 ]; then
    help
else
    if [ -n "$1" ]; then
        case "$1" in
            --user) user;;
            *) help;;
        esac
    else
        if [ "$(id -u)" = "0" ]; then
            echo "You should not use this script with uid 0!"
        else
            user
        fi
    fi
fi

exit 0

cat << END

=head1 NAME

update-lyxrc - Update LyX default configuration

=head1 SYNOPSIS

B<update-lyxrc> S<[B<--user>]>

=head1 DESCRIPTION

B<update-lyxrc> is a tool for updating system or user's LyX
configuration file. This is the same as running Tools->Reconfigure from
LyX's menu.

=head1 OPTIONS

=over 8

=item B<--system>

This function is deprecated since Lyx 1.4.2.

=item B<--user>

Update user's configuration.

=back

=head1 SEE ALSO

B<lyx>(1)

=head1 AUTHOR

(c) 2004 Piotr Roszatycki E<lt>dexter@debian.orgE<gt>.
